# Generated by Django 5.2.8 on 2026-02-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='convertida_en_pedido',
            field=models.BooleanField(default=False),
        ),
    ]
