# Generated by Django 5.2.8 on 2026-02-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cotizacion_convertida_en_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Escribe la oferta (ej: 20% de descuento en pinturas)', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
